from .discrete_laplacian import DiscreteLaplacian
from .discrete_gradient import DiscreteGradient
from .normalized_laplacian import NormalizedLaplacian
from .ornstein_uhlenbeck import OrnsteinUhlenbeck